version: "3.6"
services:
  web:
    build: ./server/
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db_data:
  server_node_modules:
