version: "3.6"
services:
  server:
    build: ./server/
    volumes:
      - server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: ["yarn", "start"]

  web:
    build: ./web
    volumes:
      - web:/app
      - ./web/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - .env

  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6.2.3
    ports:
      - "6379:6379"

volumes:
  db_data:
  server:
    driver_opts:
      type: none
      device: ${PWD}/server
      o: bind
  web:
    driver_opts:
      type: none
      device: ${PWD}/web
      o: bind
