services:
  api:
    build:
      context: ./server
      target: development
    ports:
      - "4000:4000"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - postgres
      - redis
    command: ["yarn", "start"]

  web:
    build: ./web
    ports:
      - "3000:3000"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - api

  postgres:
    build: ./db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lireddit_dev
      POSTGRES_MULTIPLE_DATABASES: lireddit_test 
      DATABASE_URL: postgres://postgres:postgres@postgres/lireddit_dev
      TEST_DATABASE_URL: postgres://postgres:postgres@postgres/lireddit_test

  redis:
    image: redis:6.2.3
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      REDIS_URL: redis:6379
    ports:
      - "6379:6379"

volumes:
  db_data:
