version: "3.6"
services:
  web:
    build: ./server/
    volumes:
      - server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_data:
  server:
    driver_opts:
      type: none
      device: ${PWD}/server
      o: bind
  server_node_modules:
    driver_opts:
      type: none
      device: ${PWD}/server/node_modules
      o: bind
